diadoc/diadocsdk-csharp

nuspec/DiadocApi.nuspec
Fix license and project urls in nuspec file
=> Fix license and project urls

Samples/Diadoc.Console/Diadoc.Console.csproj, Samples/Diadoc.Console/packages.config, Samples/Diadoc.Samples/Diadoc.Samples.csproj, Samples/Diadoc.Samples/packages.config, appveyor.yml, src/Cryptography/ExtendedWinApiCrypt.cs, src/Cryptography/StreamCrypt.cs
=> fix: vs 2012 build

proto/Invoicing/AcceptanceCertificateInfo.proto, proto/Invoicing/InvoiceInfo.proto, proto/Invoicing/Official.proto, proto/Invoicing/OrganizationInfo.proto, proto/Invoicing/Torg12Info.proto
=> proto files encoding: windows-1251 -> UTF8

proto/AcquireCounteragent.proto, proto/Events/DiadocMessage-PostApi.proto, src/Proto/AcquireCounteragent.proto.cs, src/Proto/Events/DiadocMessage-PostApi.proto.cs
=> Custom documents initial support

src/Proto/Invoicing/InvoiceInfo.cs
См. https://github.com/diadoc/diadocsdk-csharp/issues/116
=> fix COM wrappers for InvoiceInfo and CustomsDeclaration

src/ComDiadocApi.cs
=> add UTD parse seller and buyer functions to COM API

proto/Events/DiadocMessage-PostApi.proto, src/Proto/Events/DiadocMessage-PostApi.proto.cs
Отправка зашифрованных документов в формате УПД.
=> Encrypted UTD/UCD support

src/DiadocApi.cs, src/IDiadocApi.cs
Добавлен метод GenerateForwardedDocumentPrintForm в класс DiadocApi.
=> Add method GenerateForwardedDocumentPrintForm to DiadocApi

proto/Docflow/DocumentInfo.proto, proto/Documents/BilateralDocument.proto, src/Com/ComWrappers.cs, src/Proto/Docflow/DocumentInfo.proto.cs, src/Proto/Documents/BilateralDocument.proto.cs
В актах и торгах форматов 155 и 551/552 появилась возможность создавать исправления.
=> extend contract for Bilateral documents. Added optional revision date/number

src/ComDiadocApi.cs, src/DiadocApi.cs, src/DiadocHttpApi.Events.cs, src/IDiadocApi.cs
=> GetMessage performance

proto/CloudSign.proto, src/Proto/CloudSign.proto.cs
=> fix AutosignReceiptsResult proto contract

src/Com/OrganizationInvoiceFormatVersion.cs, src/Com/TaxRate.cs, src/ComDiadocApi.cs, src/DiadocApi-net35.csproj, src/DiadocApi-net45.csproj, src/Proto/Invoicing/AcceptanceCertificate552Info.cs, src/Proto/Organization.cs, tests/ComEnumsAreCompatibleWithProtoEnums_Test.cs
=> dll registration com warnings fix

src/ComDiadocApi.cs
=> Add UCD parse seller and buyer functions to COM API

src/Proto/Documents/Document.cs, src/Proto/Events/DiadocMessage.cs
Connected with https://github.com/diadoc/diadocsdk-csharp/issues/425
=> Add PacketId properties to COM interfaces

src/Proto/Organization.cs
Add LiquidationDate to COM Interface IOrganization
=> Add LiquidationDate to COM Interface IOrganization

proto/Docflow/DocflowV3.proto, src/Com/DocflowsV3.cs, src/Proto/Docflow/DocflowV3.proto.cs
change proto files and regenerate
=> Add plain texts to Docflow v3

src/DocumentsFilter.cs, tests/ComInterfaceAttributes_Test.cs
=> Add DocumentsFilter properties into COM interface

src/ComDiadocApi.cs, src/DiadocApi-net35.csproj, src/DiadocApi-net45.csproj, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.Documents.cs, src/DiadocHttpApi.DocumentsAsync.cs, src/IDiadocApi.cs, src/XsdContentType.cs
=> add contentType optional parameter to GetContent method

src/Proto/Events/DiadocMessage.cs
Add missed properties to COM for NonformalizedAttachment and XmlDocumentAttachment (like NeedReceipt)
=> Add properties to COM for NonformalizedAttachment and XmlDocumentAttachment

proto/Events/DiadocMessage-GetApi.proto, proto/Events/DiadocMessage-PostApi.proto, src/Proto/Events/DiadocMessage-GetApi.proto.cs, src/Proto/Events/DiadocMessage-PostApi.proto.cs, src/Proto/Events/DiadocMessage.cs
=> add proxy to Template

.editorconfig, src/ComDiadocApi.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.Invoicing.cs, src/DiadocHttpApi.InvoicingAsync.cs, src/IDiadocApi.cs, src/Properties/AssemblyInfo.cs, src/Properties/AssemblyVersion.cs
Use V2 version of GenerateRevocationRequestXml with new parameter "contentTypeId";
Add editor config to proper default reformat;
=> Use V2 version of GenerateRevocationRequestXml

Samples/Diadoc.Console/Properties/AssemblyVersion.cs, Samples/Diadoc.Samples/Properties/AssemblyVersion.cs, proto/Certificates/CertificateInfoV2.proto, src/Properties/AssemblyVersion.cs, src/Proto/Certificates/CertificateInfoV2.proto.cs
DDCORE-6391: Add CertificateSubjectType property for CertificateInfoV2 in GetMyCertificates Api method
=> Add CertificateSubjectType for CertificateInfoV2

proto/Workflows/DocumentWorkflowSettings.proto, src/Com/Workflows.cs, src/ComDiadocApi.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.Documents.cs, src/DiadocHttpApi.DocumentsAsync.cs, src/IDiadocApi.cs, src/Proto/Workflows/DocumentWorkflowSettings.proto.cs
* Перешёл в клиенте на вторую версию `GetWorkflowSettings`
* Добавил метод в COM API
* Старые прото-контракты пока оставил
=> Up GetWorkflowsSettings version

Samples/Diadoc.Console/Properties/AssemblyVersion.cs, Samples/Diadoc.Samples/Properties/AssemblyVersion.cs, proto/Docflow/SignaturePowerOfAttorney.proto, proto/Events/PowerOfAttorneyInfo.proto, proto/Events/PowerOfAttorneyToPost.proto, proto/PowersOfAttorney/PowerOfAttorney.proto, src/Com/DocflowsV3.cs, src/Com/PowersOfAttorney.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.PowersOfAttorney.Async.cs, src/DiadocHttpApi.PowersOfAttorney.cs, src/IDiadocApi.cs, src/Properties/AssemblyInfo.cs, src/Properties/AssemblyVersion.cs, src/Proto/Docflow/SignaturePowerOfAttorney.proto.cs, src/Proto/Events/DiadocMessage.cs, src/Proto/Events/PowerOfAttorneyInfo.proto.cs, src/Proto/Events/PowerOfAttorneyToPost.proto.cs, src/Proto/PowersOfAttorney/PowerOfAttorney.proto.cs, tests/ComEnumsAreCompatibleWithProtoEnums_Test.cs
Поддержка изменений, внесенных в апи в рамках DDCORE-7384
=> Передача МЧД файлом

proto/Events/PowerOfAttorneyToPost.proto, proto/PowersOfAttorney/PowerOfAttorney.proto, src/Com/PowersOfAttorney.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.PowersOfAttorney.Async.cs, src/DiadocHttpApi.PowersOfAttorney.cs, src/IDiadocApi.cs, src/Proto/Events/DiadocMessage.cs, src/Proto/Events/PowerOfAttorneyToPost.proto.cs, src/Proto/PowersOfAttorney/PowerOfAttorney.proto.cs
Adds support for power of attorney delegation
=> Power of attorney delegation

src/ComDiadocApi.cs, src/DiadocApi.cs, src/DiadocHttpApi.cs, tests/TaskAsyncronousPattern_Test.cs
=> Добавил информацию о технологическом решении партнёра

.github/workflows/actions.yml, build.cake
=> Fix ci build

proto/PowersOfAttorney/PowerOfAttorney.proto, src/Proto/PowersOfAttorney/PowerOfAttorney.proto.cs
Added optional third properties: `RepresentativeInn` in FullId in PowerOfAttorney
=> DDCORE-10024: add representativeInn in poa FullId

proto/PowersOfAttorney/PowerOfAttorneyValidation.proto, src/ComDiadocApi.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.PowersOfAttorney.Async.cs, src/DiadocHttpApi.PowersOfAttorney.cs, src/IDiadocApi.cs, src/Proto/PowersOfAttorney/PowerOfAttorneyValidation.proto.cs
Add new version for method PrevalidatePowerOfAttorney: PrevalidatePowerOfAttorneyV2.
=> DDCORE-10350: add V2 version PrevalidatePowerOfAttorney method

proto/Employees/PowersOfAttorney/EmployeePowerOfAttorney.proto, src/ComDiadocApi.cs, src/DiadocApi.Async.cs, src/DiadocApi.cs, src/DiadocHttpApi.Employees.PowersOfAttorney.Async.cs, src/DiadocHttpApi.Employees.PowersOfAttorney.cs, src/IDiadocApi.cs, src/Proto/Employees/PowersOfAttorney/EmployeePowerOfAttorney.proto.cs
Add V2 for methods: updateEmployeePowerOfAttorney, addEmployeePowerOfAttorney, deleteEmployeePowerOfAttorney
=> Ddcore 8469 employee poa methods v2 

src/Com/EmployeePowersOfAttorney.cs, src/Com/PowersOfAttorney.cs
Add RepresentativeInn in FullId in Com.
Add V2 interfaces and classes for EmployeePowerOfAttorneyToUpdate and PowerOfAttorneyPrevalidateRequest in Com
=> Add RepresentativeInn in Com
